---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: services
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Services Project
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: services
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: apps/services/**/system/config.json
        repoURL: https://github.com/Myrenic/Orbit.git
        requeueAfterSeconds: 20
        revision: "replace-crowdstrike-key-with-keyfile"
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
  syncPolicy: {}
  template:
    metadata:
      name: services-{{ userGivenName }}
      namespace: argocd
    spec:
      destination:
        namespace: "{{ destNamespace }}"
        server: "{{ destServer }}"
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: services
      source:
        path: "{{ srcPath }}"
        repoURL: "{{ srcRepoURL }}"
        targetRevision: "replace-crowdstrike-key-with-keyfile"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
status: {}
