---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge

resources:
  - ns.yaml
  - secrets.yaml

helmCharts:
  - name: crowdsec
    repo: https://crowdsecurity.github.io/helm-charts
    namespace: edge
    releaseName: crowdsec
    valuesFile: values.yaml
    version: 0.19.5
