---
container_runtime: containerd

secrets:
  externalSecret:
    name: crowdsec-api-token
    csLapiSecretKey: TRAEFIK_BOUNCER_KEY
    registrationTokenKey: registrationToken

lapi:
  enabled: true
  service:
    type: ClusterIP
    port: 8080
  env: 
    - name: ENROLL_INSTANCE_NAME
      value: "my-k8s-cluster"
    - name: ENROLL_TAGS
      value: "k8s linux test"
    - name: CS_LAPI_SECRET
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: csLapiSecret
    - name: REGISTRATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: registrationToken
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: ENROLL_KEY
    - name: BOUNCER_KEY_traefik
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: TRAEFIK_BOUNCER_KEY

  bouncers:
    traefik:
      keyFromSecret:
        name: crowdsec-api-token
        key: TRAEFIK_BOUNCER_KEY

console:
  enabled: true
  service:
    type: ClusterIP
    port: 8081

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
    - namespace: traefik
      file: /var/log/traefik/access.log
      program: traefik
  enabled: true
  env: 
    - name: REGISTRATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: registrationToken
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
  initContainers:
    - name: crowdsec-init
      env:
        - name: REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: crowdsec-api-token
              key: registrationToken
