---
image:
  repository: "linuxserver/jellyfin"
  tag: "10.10.7"

ports:
  - name: main
    containerPort: 8096

ingress:
  host: jellyfin.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: local-only
      namespace: edge

envs:
  - JELLYFIN_PublishedServerUrl: jellyfin.tuntelder.com
  - S6_READ_ONLY_ROOT: 1
  - PUID: 1000
  - PGID: 1000

health:
  enabled: true
  startupProbeSeconds: 220

pvcs:
  - name: jellyfin-config
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/config/jellyfin
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /config
  - name: jellyfin-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library

podSecurityContext:
  runAsNonRoot: false   
  runAsUser: 0          
  fsGroup: 1000         

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
