---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inject namespace into all resources
namespace: services

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: generic
    releaseName: radarr
    valuesFile: values.yaml
    namespace: services
