---
image:
  repository: "ghcr.io/hotio/radarr"
  tag: "release-5.28.0.10274@sha256:42ca21d9bab4df84af1898e7256256b85a04b207e72c620ac382ac4151d65dd0"

ports:
  - name: main
    containerPort: 7878

envs:
  - TZ: "Europe/Amsterdam"

ingress:
  host: radarr.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: authentik
      namespace: edge

pvcs:
  - name: radarr-config
    type: nfs
    server: 10.0.69.20
    path: /mnt/ssd_disk/config/radarr
    accessMode: ReadWriteMany
    size: 5Gi
    mountPath: /config
  - name: radarr-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
