---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: generic
    releaseName: sonarr
    valuesFile: values.yaml
    namespace: services
