---
image:
  repository: "ghcr.io/home-operations/sonarr"
  tag: "4.0.15.2940"

ports:
  - name: main
    containerPort: 8989

ingress:
  host: sonarr.tuntelder.com
  middlewares:
    - name: crowdsec-mw
      namespace: edge
    - name: authentik
      namespace: edge

pvcs:
  - name: sonarr-config
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/config/sonarr
    accessMode: ReadWriteMany
    size: 5Gi
    mountPath: /config
  - name: sonarr-library
    type: nfs
    server: 10.0.69.20
    path: /mnt/nfs_disk/media
    accessMode: ReadWriteMany
    size: 800Gi
    mountPath: /library

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
