---
container_runtime: containerd

secrets:
  externalSecret:
    name: crowdsec-api-token
    csLapiSecretKey: TRAEFIK_BOUNCER_KEY
    registrationTokenKey: registrationToken

lapi:
  config:
    notifications:
      telegram:
        type: telegram
        tokenFromSecret:
          name: crowdsec-api-token
          key: TELEGRAM_BOT_TOKEN
        chat_ids:
          - -1003081346556
        topics:
          - 2
        enabled: true
  enabled: true
  service:
    type: ClusterIP
    port: 8080
  env: 
    - name: ENROLL_INSTANCE_NAME
      value: "my-k8s-cluster"
    - name: ENROLL_TAGS
      value: "k8s linux test"
    - name: CS_LAPI_SECRET
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: csLapiSecret
    - name: REGISTRATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: registrationToken
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: ENROLL_KEY
    - name: BOUNCER_KEY_traefik
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: TRAEFIK_BOUNCER_KEY

  bouncers:
    traefik:
      keyFromSecret:
        name: crowdsec-api-token
        key: TRAEFIK_BOUNCER_KEY

console:
  enabled: true
  service:
    type: ClusterIP
    port: 8081

agent:
  enabled: true
  additionalAcquisition:
    - source: file
      filenames:
        - '/var/logs/traefik/traefik.log'     ## Single file
      labels:
        type: traefik
  extraVolumes:
    - name: traefik-logs
      persistentVolumeClaim:
        claimName: traefik-logs-pvc
  extraVolumeMounts:
    - name: traefik-logs
      mountPath: /var/logs/traefik/
  env: 
    - name: REGISTRATION_TOKEN
      valueFrom:
        secretKeyRef:
          name: crowdsec-api-token
          key: registrationToken
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
  initContainers:
    - name: crowdsec-init
      env:
        - name: REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: crowdsec-api-token
              key: registrationToken
