---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world
  namespace: services
spec:
  containers:
    - name: hello-world-container
      image: crccheck/hello-world
      ports:
        - containerPort: 8000
