---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: network
spec:
  addresses:
    - 10.0.3.190-10.0.3.199
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool
  namespace: network
spec:
  ipAddressPools:
    - pool
