---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: edge
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.69.201
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443
    - name: admin
      port: 8080
      targetPort: 8080
  selector:
    app: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingressroute
  namespace: edge
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.tuntelder.com`)
      kind: Rule
      services:
        - name: traefik
          port: 8080
      middlewares:
        - name: crowdsec-mw
          namespace: edge
        - name: local-only
          namespace: edge
  tls:
    certResolver: letsencrypt