image:
  repository: "quay.io/minio/minio"
  tag: "RELEASE.2025-04-22T22-12-26Z@sha256:a1ea29fa28355559ef137d71fc570e508a214ec84ff8083e39bc5428980b015e"

ports:
  - name: main
    containerPort: 9001
  - name: api
    containerPort: 9000

ingress:
  host: minio.testlab.tuntelder.com

args:
  - server
  - /data
  - --console-address=:9001

secretEnvs:
  - MINIO_ROOT_USER: AgBSgmseeIv69rHAKd1IzQ6jFSD/7DPUUQZsUdz2LxkCinPNqJ5Irmt2wnMJYiF1db/XBbTlauIik58KNNjin9Mnmqe/+5MxeUot6+4ZGLjvMupT54IgQ1WtQmxU6S/DwD1eXAwAJsLAaWQ81/yjilQjBVez4HX28oY9W16vFWuL1KiGq0Lz9CDhOGuZDAVpGpfTG/R85DmgJdYKBFJLNGdq/M7WZGNNZnmIZto7VTEB+MjPPD8ij9hwXZVy6h8U4vXxskL/Im8AX/5WFxrwaktZLo88/SBYo/+eU1Od/ji2G4c0r0UvOMY15UEQuXR+m2MatD6QrXTG0kqUnTcoN500N3ySJmdxITZm8GIrBzNYI/l5XuYan/hoWy3AzVL/HKXw7axolwkLowVqdXmVuH7osbNhQ/XdLGYgdWYV9HSQih2FvI9JTjSXeuGMYYVntZXhEMT+/ad3T7LULeOHw60oMDxYDntg+FWmZcuAJsf8hqdp1VkYqAptnOYONtC6I8YvQ9EBQlBuf/Ulk99ehp5d/D5897RobXtpnf3W3hblSOI1gkt3WCfIjNQfOYzFJh7Gw/JbQYFEKJ6fbgBkICFpAfeZ6ceD2jpP8hAzgSbznILNRaNDzYj3l9tyq8FnWiOSl2py3fiuwqu79G9sFSVhKz1Hkhy0x3URSj+yPeg3WeJJcMkWI0yDYWBVjwrAFQGPcvGUlfaNAnO3
  - MINIO_ROOT_PASSWORD: AgAUDu7IZLd4BT72Cfn5LBhYHW2bdDCE+oy258DU+YYWYQqHUjJEgNBnoDfr/0PvG6UypZP6J96yhGo/7cwkv5MZWjAWh4b9KljB1+0xrrpX1Qpr5o+2Ob3a5cayqgDWnUfG8Rno4Kbd+xi+1FAjD7cjq8lHcg6kQN0HqskjI6K8FwYLcGmxCXdkPhjzDdg3DPSjdsLDFQ7e/SisZLpoSAcP6z9Eiki0aLMBITTsaMLlLfueGdGichjDZtc4JO3WW5p+FNBUtFM/nUJZEmNPRo5AvfUlAmC8oLeCX7pK4iQOBgu354d89pmpxeHLja2y62lSo4egfFT6kShmuABohBq3F3Pgc/8hsTcPyMlIdBCA232ihynqreVzqbNeWmSUiX6tsbIvauIHvT+9Zk/Hrs+jeeximGC77+5vnGPaZjdTtuN4YzGgwiu6zIzMJh9NkKXgzodRcRaUT6fAwNlayYMTfGBGQ2AFX5LNoEOerTQrVkzgVwvzk5kZPySgsgKjF79XT8enDNMiuLq3AWUdDae840QTPbdTpff+vS3HmnB3f8MZgnVQtMQnxyOQFlrUvSHEnYEUS929iS8znhOKdXrw5X4p9ouPL/rEjp323rFlJBzBcY7Z05dz9MAP1gL+nlgLY+dSkQzpIu+6v2FQFR6oqxw0DcpITtxHwDL9MmM3ulyEY8keNEGRKz/xcywTudcfSBXfdJrRuZbbNOI=

hostPaths:
  - name: app-data
    type: longhorn
    size: 20Gi
    accessMode: ReadWriteOnce
    mountPath: /data
