image:
  tag: v1.106.1   # pick the Immich version you want to run

immich:
  persistence:
    library:
      enabled: true
      existingClaim: immich-library-pvc
    uploads:
      enabled: true
      existingClaim: immich-uploads-pvc

  redis:
    enabled: true   # let the chart deploy Redis for you

  postgresql:
    enabled: true  # chart doesnâ€™t provide Postgres
    host: immich-postgres
    port: 5432
    user: immich
    password: supersecret
    database: immich

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: immich.tuntelder.com
        paths:
          - path: /
            pathType: Prefix
