---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.tuntelder.com`)
      kind: Rule
      services:
        - name: home-assistant-nginx
          port: 80

  tls:
    certResolver: letsencrypt
