---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create the namespace first
resources:
  - ns.yaml

# Inject namespace into all resources
namespace: aiostreams

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: generic
    releaseName: aiostreams
    valuesFile: values.yaml
    namespace: aiostreams
